### ISSUE TITLE
🐛 [BUG] - Error 500 instead of 404 on product page when changing id of product

### ISSUE THREAD

**Issue by sparh** [Oksydan/falcon#150]
### Description

Hello,
on product page when using a false product id example https://falcon-theme.dev/pl/art/5555-the-best-is-yet-to-come-framed-poster.html#/19-dimension-40x60cm there is an error 500 instead of the usual 404 page.
It affect all version of the theme and is_themecore.

### Node.js version

v14

### php version

v7.4

### OS and it's version

Windows

### Browsers

Chrome

### Required module/theme

is_themecore

### Reproduction steps

```bash
1. Go to a product page
2. In the url replace product id with one which do not exists
3. Blank page (error 500) instead of the usual 404 page
```

### Logs

```bash
[Thu Dec 01 10:44:42.393526 2022] [proxy_fcgi:error] [pid 10429:tid 140461377308416] [client 194.230.146.16:3679] AH01071: Got error 'PHP message: PHP Notice:  Trying to access array offset on value of type null in /home//public_html/controllers/front/ProductController.php on line 1168PHP message: PHP Notice:  Trying to access array offset on value of type null in /home/public_html/controllers/front/ProductController.php on line 1168PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to ProductControllerCore::addProductCustomizationData() must be of the type array, bool given, called in /home//public_html/controllers/front/ProductController.php on line 1118 and defined in /home/public_html/controllers/front/ProductController.php:1270\nStack trace:\n#0 /home/public_html/controllers/front/ProductController.php(1118): ProductControllerCore->addProductCustomizationData()\n#1 /home/public_html/modules/is_themecore/src/Core/StructuredData/Provider/StructuredDataProductProvider.php(14): ProductControllerCore->getTemplateVarProduct()\n#2 /home/public_html/modules/is_themecore/src/Hook/Header.php(75): Oksydan\\Module\\IsThemeCore\\Core\\StructuredData\\Provider\\StructuredDataProductProvider->__construct()\n#3 /home/public_html/modules/is_th...'
```

**Comment by Oksydan** [comment]
Hi @sparh,

thank you for your report.
I was able to reproduce an issue.

**Comment by Oksydan** [comment]
Hi @sparh,

new version of is_themecore [2.3.1](https://github.com/Oksydan/is_themecore/releases/tag/v2.3.1) and [3.0.1](https://github.com/Oksydan/is_themecore/releases/tag/v3.0.1) has been released. 
Problem has been solved and I am closing this issue. 
Thank you for your contribution.
