### ISSUE TITLE
🐛 [BUG] - Build error

### ISSUE THREAD

**Issue by slawekmoskal** [Oksydan/falcon#184]
### Description

Error using "build"

### Node.js version

v18.12

### php version

8.0

### OS and it's version

MacOS Monterey ARM

### Browsers

Safari

### Required module/theme

theme

### Reproduction steps

```bash
1. Yarn install inside _dev folder - (log_1) - ok
2. Yarn build - log_2 (error)
3. Yarn project-ini - log_3 error
4. Try npm (install and build) - log_4 (error / warning scss)
5. Try npm install -g npm-check-updates, ncu -u, npm install - log_5
```

### Logs

```bash
log_1 (install)
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
✨  Done in 9.13s.




------------------------------------------------------------------------------------
log_2 (build)
yarn run v1.22.19
$ webpack --progress --mode=production --env stats=errors-only
10% building 0/8 entries 8/8 dependencies 0/8 modules/Users/slawek/Documents/projekty_ws/2023/ta/public_html/themes/falcon/_dev/node_modules/loader-runner/lib/LoaderRunner.js:119
                        throw new Error("callback(): The callback was already called.");
                              ^

Error: callback(): The callback was already called.
    at context.callback (/Users/slawek/Documents/projekty_ws/2023/ta/public_html/themes/falcon/_dev/node_modules/loader-runner/lib/LoaderRunner.js:119:10)
    at Object.ESBuildLoader (/Users/slawek/Documents/projekty_ws/2023/ta/public_html/themes/falcon/_dev/node_modules/esbuild-loader/dist/loader.js:62:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.12.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.




------------------------------------------------------------------------------------
log_3
yarn run v1.22.19
$ falcon-cli init
/Users/Sławek/Documents/projekty_ws/2023/ta/public_html/themes/falcon/_dev/node_modules/@oksydan/falcon-cli/index.js:9
  error(
  ^

TypeError: error is not a function
    at Object.<anonymous> (/Users/slawek/Documents/projekty_ws/2023/ta/public_html/themes/falcon/_dev/node_modules/@oksydan/falcon-cli/index.js:9:3)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.12.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.




------------------------------------------------------------------------------------
log_4
10% building 0/8 entries 8/8 dependencies 0/8 modulesDeprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(1, $rfs-rem-value) or calc(1 / $rfs-rem-value)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
49 │   $rfs-base-font-size: $rfs-base-font-size / ($rfs-base-font-size * 0 + 1 / $rfs-rem-value);
   │                                                                         ^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/bootstrap/scss/vendor/_rfs.scss 49:73  @import
    node_modules/bootstrap/scss/_mixins.scss 6:9        @import
    css/abstracts/_index.scss 2:9                       @import
    css/theme.scss 1:9                                  root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($rfs-base-font-size, $rfs-base-font-size * 0 + 1 / $rfs-rem-value) or calc($rfs-base-font-size / ($rfs-base-font-size * 0 + 1 / $rfs-rem-value))

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
49 │   $rfs-base-font-size: $rfs-base-font-size / ($rfs-base-font-size * 0 + 1 / $rfs-rem-value);
   │                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/bootstrap/scss/vendor/_rfs.scss 49:24  @import
    node_modules/bootstrap/scss/_mixins.scss 6:9        @import
    css/abstracts/_index.scss 2:9                       @import
    css/theme.scss 1:9                                  root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(1, $rfs-rem-value) or calc(1 / $rfs-rem-value)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
49 │   $rfs-base-font-size: $rfs-base-font-size / ($rfs-base-font-size * 0 + 1 / $rfs-rem-value);
   │                                                                         ^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/bootstrap/scss/vendor/_rfs.scss 49:73  @import
    node_modules/bootstrap/scss/_mixins.scss 6:9        @import
    css/abstracts/_index.scss 2:9                       @import
    css/checkout.scss 1:9                               root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($rfs-base-font-size, $rfs-base-font-size * 0 + 1 / $rfs-rem-value) or calc($rfs-base-font-size / ($rfs-base-font-size * 0 + 1 / $rfs-rem-value))

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
49 │   $rfs-base-font-size: $rfs-base-font-size / ($rfs-base-font-size * 0 + 1 / $rfs-rem-value);
   │                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/bootstrap/scss/vendor/_rfs.scss 49:24  @import
    node_modules/bootstrap/scss/_mixins.scss 6:9        @import
    css/abstracts/_index.scss 2:9                       @import
    css/checkout.scss 1:9                               root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(1, $rfs-rem-value) or calc(1 / $rfs-rem-value)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
49 │   $rfs-base-font-size: $rfs-base-font-size / ($rfs-base-font-size * 0 + 1 / $rfs-rem-value);
   │                                                                         ^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/bootstrap/scss/vendor/_rfs.scss 49:73  @import
    node_modules/bootstrap/scss/_mixins.scss 6:9        @import
    css/abstracts/_index.scss 2:9                       @import
    css/product.scss 1:9                                root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($rfs-base-font-size, $rfs-base-font-size * 0 + 1 / $rfs-rem-value) or calc($rfs-base-font-size / ($rfs-base-font-size * 0 + 1 / $rfs-rem-value))

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
49 │   $rfs-base-font-size: $rfs-base-font-size / ($rfs-base-font-size * 0 + 1 / $rfs-rem-value);
   │                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/bootstrap/scss/vendor/_rfs.scss 49:24  @import
    node_modules/bootstrap/scss/_mixins.scss 6:9        @import
    css/abstracts/_index.scss 2:9                       @import
    css/product.scss 1:9                                root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(1, $rfs-rem-value) or calc(1 / $rfs-rem-value)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
49 │   $rfs-base-font-size: $rfs-base-font-size / ($rfs-base-font-size * 0 + 1 / $rfs-rem-value);
   │                                                                         ^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/bootstrap/scss/vendor/_rfs.scss 49:73  @import
    node_modules/bootstrap/scss/_mixins.scss 6:9        @import
    css/abstracts/_index.scss 2:9                       @import
    css/listing.scss 1:9                                root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($rfs-base-font-size, $rfs-base-font-size * 0 + 1 / $rfs-rem-value) or calc($rfs-base-font-size / ($rfs-base-font-size * 0 + 1 / $rfs-rem-value))

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
49 │   $rfs-base-font-size: $rfs-base-font-size / ($rfs-base-font-size * 0 + 1 / $rfs-rem-value);
   │                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/bootstrap/scss/vendor/_rfs.scss 49:24  @import
    node_modules/bootstrap/scss/_mixins.scss 6:9        @import
    css/abstracts/_index.scss 2:9                       @import
    css/listing.scss 1:9                                root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($rfs-breakpoint, $rfs-breakpoint * 0 + 1) or calc($rfs-breakpoint / ($rfs-breakpoint * 0 + 1))

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
57 │   $rfs-breakpoint: $rfs-breakpoint / ($rfs-breakpoint * 0 + 1);
   │                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/bootstrap/scss/vendor/_rfs.scss 57:20  @import
    node_modules/bootstrap/scss/_mixins.scss 6:9        @import
    css/abstracts/_index.scss 2:9                       @import
    css/theme.scss 1:9                                  root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($rfs-breakpoint, $rfs-breakpoint * 0 + 1) or calc($rfs-breakpoint / ($rfs-breakpoint * 0 + 1))

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
57 │   $rfs-breakpoint: $rfs-breakpoint / ($rfs-breakpoint * 0 + 1);
   │                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/bootstrap/scss/vendor/_rfs.scss 57:20  @import
    node_modules/bootstrap/scss/_mixins.scss 6:9        @import
    css/abstracts/_index.scss 2:9                       @import
    css/checkout.scss 1:9                               root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($rfs-breakpoint, $rfs-breakpoint * 0 + 1) or calc($rfs-breakpoint / ($rfs-breakpoint * 0 + 1))

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
57 │   $rfs-breakpoint: $rfs-breakpoint / ($rfs-breakpoint * 0 + 1);
   │                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/bootstrap/scss/vendor/_rfs.scss 57:20  @import
    node_modules/bootstrap/scss/_mixins.scss 6:9        @import
    css/abstracts/_index.scss 2:9                       @import
    css/product.scss 1:9                                root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($rfs-breakpoint, $rfs-breakpoint * 0 + 1) or calc($rfs-breakpoint / ($rfs-breakpoint * 0 + 1))

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
57 │   $rfs-breakpoint: $rfs-breakpoint / ($rfs-breakpoint * 0 + 1);
   │                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/bootstrap/scss/vendor/_rfs.scss 57:20  @import
    node_modules/bootstrap/scss/_mixins.scss 6:9        @import
    css/abstracts/_index.scss 2:9                       @import
    css/listing.scss 1:9                                root stylesheet

/Users/Sławek/Documents/projekty_ws/2023/ta/public_html/themes/falcon/_dev/node_modules/loader-runner/lib/LoaderRunner.js:119
                        throw new Error("callback(): The callback was already called.");
                              ^

Error: callback(): The callback was already called.
    at context.callback (/Users/slawek/Documents/projekty_ws/2023/ta/public_html/themes/falcon/_dev/node_modules/loader-runner/lib/LoaderRunner.js:119:10)
    at Object.ESBuildLoader (/Users/slawek/Documents/projekty_ws/2023/ta/public_html/themes/falcon/_dev/node_modules/esbuild-loader/dist/loader.js:62:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.12.0



------------------------------------------------------------------------------------
log_5

ERROR in ./css/theme.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.......
```

**Comment by Oksydan** [comment]
HI @slawekmoskal,

I am going to close this issue since it's a duplication.
