### ISSUE TITLE
🐛 [BUG] - Unable to build on _dev dir

### ISSUE THREAD

**Issue by augustomurri** [Oksydan/falcon#209]
### Description

Hi all, i have installed theme and modules but when i run **npm run build** i get this error i don't know how to solve

### Node.js version

v16.20.0

### php version

v7.4.33

### OS and it's version

Debian 11

### Required module/theme

theme

### Reproduction steps

```bash
problem on clean install v 2.X
```

### Logs

```bash
root@TSUNAMINUTRITION-COM:/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev# npm run build

> modern-prestashop-build-tool@2.3.1 build
> webpack --progress --mode=production --env stats=errors-only

[webpack-cli] Failed to load '/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/webpack.config.js' config
[webpack-cli] /var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/hot-accept-webpack-plugin/build/HotAcceptPlugin.js:9
            const moduleRequest = module.userRequest?.replace(/\\/g, '/');
                                                     ^

SyntaxError: Unexpected token '.'
    at new Script (vm.js:88:7)
    at NativeCompileCache._moduleCompile (/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/hot-accept-webpack-plugin/build/index.js:13:14)
    at Module._compile (/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
root@TSUNAMINUTRITION-COM:/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev# node -v
v16.20.0
root@TSUNAMINUTRITION-COM:/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev# nano /var/www/tsunaminutrition.com/info.php
root@TSUNAMINUTRITION-COM:/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev# cat /etc/issue
Debian GNU/Linux 11 \n \l

root@TSUNAMINUTRITION-COM:/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev#
```

**Comment by Oksydan** [comment]
Hi @augustomurri,

It is crashing with optional chaining operator 🤔. 
I have no idea why isn't not working properly. 
Could you use recommended version from `.nvmrc` file https://github.com/Oksydan/falcon/blob/v2.3.1/_dev/.nvmrc altho it should work properly with node 16.

**Comment by augustomurri** [comment]
Mmm i am not very handy with node

`root@TSUNAMINUTRITION-COM:/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev# nvm install 14.17.3
Downloading and installing node v14.17.3...
Downloading https://nodejs.org/dist/v14.17.3/node-v14.17.3-linux-x64.tar.xz...
############################################################################################################################################################################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v14.17.3 (npm v6.14.13)
root@TSUNAMINUTRITION-COM:/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev# node --version
v14.17.3
root@TSUNAMINUTRITION-COM:/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev# npm run build

> modern-prestashop-build-tool@2.3.1 build /var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev
> webpack --progress --mode=production --env stats=errors-only

10% building 0/8 entries 8/8 dependencies 0/8 modules/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/esbuild/bin/esbuild:2
throw new Error(`esbuild: Failed to install correctly
^

Error: esbuild: Failed to install correctly

Make sure you don't have "ignore-scripts" set to true. You can check this with
"npm config get ignore-scripts". If that returns true you can reset it back to
false using "npm config set ignore-scripts false" and then reinstall esbuild.

If you're using npm v7, make sure your package-lock.json file contains either
"lockfileVersion": 1 or the code "hasInstallScript": true. If it doesn't have
either of those, then it is likely the case that a known bug in npm v7 has
corrupted your package-lock.json file. Regenerating your package-lock.json file
should fix this issue.

    at Object.<anonymous> (/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/esbuild/bin/esbuild:2:7)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
[webpack-cli] HookWebpackError: The service is no longer running
    at makeWebpackError (/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/webpack/lib/Compilation.js:3060:12
    at eval (eval at create (/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:85:1)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
-- inner error --
Error: The service is no longer running
    at /var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/esbuild/lib/main.js:1261:29
    at sendRequest (/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/esbuild/lib/main.js:610:14)
    at start (/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/esbuild/lib/main.js:1259:9)
    at Object.transform2 [as transform] (/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/esbuild/lib/main.js:1309:5)
    at /var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/esbuild/lib/main.js:1829:55
    at new Promise (<anonymous>)
    at Object.transform (/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/esbuild/lib/main.js:1829:14)
    at ESBuildMinifyPlugin.transform (/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/esbuild/lib/main.js:1660:62)
    at /var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/esbuild-loader/dist/minify-plugin.js:75:39
    at Array.map (<anonymous>)
caused by plugins in Compilation.hooks.processAssets
Error: The service is no longer running
    at /var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/esbuild/lib/main.js:1261:29
    at sendRequest (/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/esbuild/lib/main.js:610:14)
    at start (/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/esbuild/lib/main.js:1259:9)
    at Object.transform2 [as transform] (/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/esbuild/lib/main.js:1309:5)
    at /var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/esbuild/lib/main.js:1829:55
    at new Promise (<anonymous>)
    at Object.transform (/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/esbuild/lib/main.js:1829:14)
    at ESBuildMinifyPlugin.transform (/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/esbuild/lib/main.js:1660:62)
    at /var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev/node_modules/esbuild-loader/dist/minify-plugin.js:75:39
    at Array.map (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! modern-prestashop-build-tool@2.3.1 build: `webpack --progress --mode=production --env stats=errors-only`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the modern-prestashop-build-tool@2.3.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-04-11T14_41_28_627Z-debug.log
root@TSUNAMINUTRITION-COM:/var/www/tsunaminutrition.com/themes/tsunaminutrition/_dev# 
`

**Comment by augustomurri** [comment]
Ok solved by installing **esbuild**

`
npm install esbuild
`

**Comment by Oksydan** [comment]
That’s odd. Esbuild should be installed with esbuild-loader. 
I happy that you managed to solve it. I am closing this issue. Feel free to open new issue if you face any problem.
