### ISSUE TITLE
🐛 [BUG] - "{images_block}" unknown tag 'images_block' in module:is_imagesliderviewstemplateshookslider.tpl

### ISSUE THREAD

**Issue by fdch** [Oksydan/falcon#256]
### Description

I'm trying to install falcon, but I got an error on smarty. It seems the `image_tag` is not loaded.
I'm running git master branch versions of falcon and all its dependency modules. PS with `prestashop/prestashop:8.0.5-apache docker` image.
I've compiled `is_imageslider` with its `make` and installed it first by copying files. BO interface works, FO fails with the error I copy below. Then, the same thing happens if I install the module using the produced zip file and the BO upload way.

### Node.js version

v18.12.1

### php version

v8.1.22

### OS and it's version

linuz (docker linux/amd64)

### Browsers

Firefox

### Required module/theme

is_imageslider

### Reproduction steps

```bash
1. load the theme
2. go to view site
3. 💥 error message
```

### Logs

```bash
Fatal error: Uncaught SmartyCompilerException: Syntax error in template "module:module:is_imagesliderviewstemplateshookslider.tpl" on line 36 "{images_block}" unknown tag 'images_block' in module:is_imagesliderviewstemplateshookslider.tpl:36 Stack trace: #0 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php(1746): Smarty_Internal_TemplateCompilerBase->trigger_template_error('unknown tag 'im...', 36, true) #1 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php(550): Smarty_Internal_TemplateCompilerBase->compileTag2('images_block', Array, Array) #2 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templateparser.php(2104): Smarty_Internal_TemplateCompilerBase->compileTag('images_block', Array) #3 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templateparser.php(2777): Smarty_Internal_Templateparser->yy_r12() #4 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templateparser.php(2872): Smarty_Internal_Templateparser->yy_reduce(12) #5 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_smartytemplatecompiler.php(128): Smarty_Internal_Templateparser->doParse(3, '\n ') #6 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php(466): Smarty_Internal_SmartyTemplateCompiler->doCompile('<!-- begin /var...', true) #7 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php(395): Smarty_Internal_TemplateCompilerBase->compileTemplateSource(Object(SmartyDevTemplate), false, NULL) #8 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(184): Smarty_Internal_TemplateCompilerBase->compileTemplate(Object(SmartyDevTemplate)) #9 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(141): Smarty_Template_Compiled->compileTemplateSource(Object(SmartyDevTemplate)) #10 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(105): Smarty_Template_Compiled->process(Object(SmartyDevTemplate)) #11 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render(Object(SmartyDevTemplate)) #12 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render(false, 0) #13 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute(Object(SmartyDevTemplate), NULL, NULL, NULL, 0) #14 /var/www/html/classes/Smarty/SmartyDevTemplate.php(55): Smarty_Internal_TemplateBase->fetch(NULL, NULL, NULL, NULL) #15 /var/www/html/classes/module/Module.php(2269): SmartyDevTemplateCore->fetch() #16 /var/www/html/modules/is_imageslider/src/Hook/AbstractCacheableDisplayHook.php(56): ModuleCore->fetch('module:is_image...', 'is_imageslider|...') #17 /var/www/html/modules/is_imageslider/is_imageslider.php(113): Oksydan\IsImageslider\Hook\AbstractCacheableDisplayHook->execute(Array) #18 /var/www/html/classes/Hook.php(983): Is_imageslider->__call('hookDisplayHome', Array) #19 /var/www/html/classes/Hook.php(409): HookCore::coreCallHook(Object(Is_imageslider), 'hookDisplayHome', Array) #20 /var/www/html/classes/Hook.php(918): HookCore::callHookOn(Object(Is_imageslider), 'displayHome', Array) #21 /var/www/html/controllers/front/IndexController.php(40): HookCore::exec('displayHome') #22 /var/www/html/classes/controller/Controller.php(319): IndexControllerCore->initContent() #23 /var/www/html/classes/Dispatcher.php(510): ControllerCore->run() #24 /var/www/html/index.php(28): DispatcherCore->dispatch() #25 {main} Next PrestaShop\PrestaShop\Core\Exception\CoreException: Syntax error in template "module:module:is_imagesliderviewstemplateshookslider.tpl" on line 36 "{images_block}" unknown tag 'images_block' in /var/www/html/classes/Hook.php:422 Stack trace: #0 /var/www/html/classes/Hook.php(918): HookCore::callHookOn(Object(Is_imageslider), 'displayHome', Array) #1 /var/www/html/controllers/front/IndexController.php(40): HookCore::exec('displayHome') #2 /var/www/html/classes/controller/Controller.php(319): IndexControllerCore->initContent() #3 /var/www/html/classes/Dispatcher.php(510): ControllerCore->run() #4 /var/www/html/index.php(28): DispatcherCore->dispatch() #5 {main} thrown in /var/www/html/classes/Hook.php on line 422
```

**Comment by Oksydan** [comment]
HI @fdch,

thank you for creating an issue. 
Did you download every required module as releases and extract them to your module folder.
Looks like your is_themecore module isn't installed properly. 
Can you try to download it again from releases and install it in your store?

**Comment by fdch** [comment]
As I mentioned in the description, I cloned and ran `make` on every required module, then installed with the respective zip file.
I can try downloading it from releases and installing it in the store.

**Comment by nukdokplex** [comment]
same here, downloaded is_themecore.zip from releases and unpacked to modules folder. Same error appeared

**Comment by Oksydan** [comment]
Hi @fdch and @nukdokplex,

is your is_themecore module registered to `actionDispatcherBefore` in this hook we register that image smarty block. 
BTW don't install modules and then theme. You should add your modules to your modules folder and every **required** module will be installed during theme installation process. 
Installing modules and then theme might unregister multiple hooks for your store.

**Comment by fdch** [comment]
Thanks. Here's what I did to install: The theme failed to install because the required modules were missing, so I added them one by one until the theme installed correctly. Did this affect the hook registration?

**Comment by Oksydan** [comment]
Shouldn't 🤔. Is your `is_themecore` module registered to `actionDispatcherBefore` hook?
Is your symfony container up to date? You can run `bin/console c:c` to clear cache of your symfony container. Since every hook in `is_themecore` module is a service and if sf container isn't aware of those services it will not run them.

**Comment by nukdokplex** [comment]
Cache clear helped, Thanks!

**Comment by Oksydan** [comment]
Hi @fdch,

Since we haven't heard from you in 3 weeks I am closing this issue.
Feel free to open new one.
